name = "nexaflow"
compatibility_date = "2023-10-30"

[build]
command = "npm run build"
cwd = "."
watch_dir = "src"

[build.environment]
NODE_VERSION = "18"

# Cloudflare Pages Configuration
[env.production]
name = "nexaflow"

# تحسينات الأداء
[vars]
NODE_ENV = "production"
VITE_ENVIRONMENT = "production"

# إعدادات Cache للملفات الثابتة
[[headers]]
for = "*.js"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.css"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.woff2"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.webp"
[headers.values]
Cache-Control = "public, max-age=86400"